### ISSUE TITLE
¿How to grenerate a runnable jar witthin eclipse?

### ISSUE THREAD

**Issue by jneira** [Frege/eclipse-plugin#22]
Hi, i am trying the frege eclipse plugin and it works as expected.
However i dont find the way to generate a runnable jar: if you use the jar export option, the generated jar doesnt include the class files, only the .fr source ones. The class files are in the target folder and i can run the application
Maybe i am missing some eclipse option...

Thanks and congrats

**Comment by Ingo60** [comment]
Hi, I suspect that the normal way (i.e. right click the project in project explorer, Export ..., Java, Executable Jar) doesn't work as expected because this is somehow linked to the Java Builder, and this builder apparently refuses to accept the existence of class files it didn't create itself.

To be honest, I've never tried that before, as I always have a project I can build without Eclipse from the commandline. I also prefer to run stuff from the commandline, as I find the Run Configuration as too unflexible. For example, when I want to run the code with diferent command line arguments, I'm definitely faster switching to my terminal, hiting the UP cursor key, and  editing the previous command line. If it's a file name, this has the additional benefit that I have sh-support (i.e. tab completion). The same holds for changed JVM parameters, or a different java (for example, 7 vs. 8).

Note that you don't even need a build tool to merely run what Eclipse has built.

For JAR generation, you do have the choice among maven, gradle, leiningen, sbt and even bazel. And if that isn't good enough, you can still write your own Makefile.

**Comment by jneira** [comment]
Thanks for your reply, i agree with you that the best way is to use some build tool like maven or gradle which can be integrated with eclipse.
