### ISSUE TITLE
Compile errors don't show up in "Problems" view.

### ISSUE THREAD

**Issue by muhuk** [Frege/eclipse-plugin#8]
![screenshot18](https://cloud.githubusercontent.com/assets/40178/5992099/a0bb58fe-aa20-11e4-974d-ff7ead18ba09.png)

(Couldn't capture the tooltip, but it is shown.)

Eclipse version: Luna Service Release 1a (4.4.1) (Build id: 20150109-0600)

Plugin version: Frege Development 3.22.335.201501171835

**Comment by muhuk** [comment]
Fantastic. Clean & rebuild seems to fix it.

Eclipse... :/

**Comment by Ingo60** [comment]
For an explanation: the problem view is only populated when a file is actually compiled (rather than just briefly examined while you type). In "Build Automatically" mode a file gets normally compiled only after  you changed something and saved (Ctrl+S).

The state you were in can be reached by quitting Eclipse without having corrected all the errors. This way the Problems View gets cleared, and when you reopen, you have an unchanged file with errors that are not shown in the problem view.

You can force compilation of the active file anytime with the "Compile" button. This way, the builder is forcibly triggered by the workbench.

Or, of course, with project rebuild as you already found, which is ok for small projects with a handful of files.
